server:
  port: 8888
spring:
  #数据源
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/orange?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: xxxxx
    password: xxxxx
  #redis
  redis:
    host: xxxxx
    port: 6379
    redis:
      jedis:
        pool:
          max-active: 50
          max-wait: 3000
          max-idle: 20
          min-idle: 5
    timeout: 4000
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  application:
    name: orange-api
#nacos:
#  config: xxxxxxx


